### PR TITLE
Directions

### PR DESCRIPTION
**Pull request by EvilPudding**
I didn't really know what to name them, and was trying to come up with a
name that stayed compatible with the current approach, but failed any good
ideas?

### CODE REVIEW

**Comment by kovetskiy** [comment]
@EvilPudding thank you for the contribution, but can you squash your two commits to one commit?

I think we should not use geo directions and use more obvious terms: `South`->`Up`, `North`->`Down`, `East`->`Deep` and `West`->`Shallow`.

Also I think we should save the compatibility with old plugin versions, so it would be very well to have aliases (additional user commands in viml, I guess) like as following:

```
IndentationGoUpPy -> IndentationGoUpShallowPy
IndentationGoDownPy -> IndentationGoDownDeepPy
```

**Comment by EvilPudding** [comment]
That was one of my thoughts, but I figured shallow would be too long a word.
Why would you wan't me to "squash" the two commits into one?

**Comment by kovetskiy** [comment]
@EvilPudding 

> That was one of my thoughts, but I figured shallow would be too long a word.

Yeah, but obviousness is more important thing than length of words.

> Why would you wan't me to "squash" the two commits into one?

I think it's not good to have the 'Bug fix.' commits in git log tree for a features.

**Comment by EvilPudding** [comment]
Then pull the commits individually, "Bug fix" is a good summary of what was made in that commit.

**Comment by seletskiy** [comment]
@EvilPudding: I guess @kovetskiy's point was in using more descriptive subject line for the commit message, not just "Bug fix", which says nothing about what bug was fixed when viewing oneline git log (most usable).

In your case it will be better to use something like "fix premature shallow navigation stop"

**Comment by EvilPudding** [comment]
That would be terrible for the commit summary, but not for the commit full description.
"Bug fix" is a good summary, and what @kovetskiy said was:

> I think it's not good to have the 'Bug fix.' commits in git log tree for a features.

Which seems to imply that the name is bad, when the issue is about adding a feature.
Mixing the two commits, like he suggested, wouldn't make the commit name more descriptive, but the opposite. Never merge two commits into one, that do completely different things...

**Comment by seletskiy** [comment]
@EvilPudding: Can you describe, why do you think that my variant is terrible?

**Comment by EvilPudding** [comment]
I didn't say yours was terrible, it's great even.
What I was saying is that that isn't what @kovetskiy was complaining about, he didn't ask for a better name for my commit, he asked to squash them into one, which would hide the fact that there is a bug fix in the changes. He said having "bug fix" in a feature pull request would look bad in the git log, which makes no sense.

**Comment by seletskiy** [comment]
@EvilPudding: Thanks for the discussion, I just misunderstood your first sentence, my bad.

**Pull request closed without merging**
